steps:
  # Build the frontend image with build arguments
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGISTRY}/${PROJECT_ID}/${_SERVICE_NAME}:latest'
      - '--build-arg'
      - 'BACKEND_URL=${_BACKEND_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_BACKEND_URL=${_NEXT_PUBLIC_BACKEND_URL}'
      - '.'

images:
  - '${_REGISTRY}/${PROJECT_ID}/${_SERVICE_NAME}:latest'

substitutions:
  _REGISTRY: 'gcr.io'
  _SERVICE_NAME: 'data-qa-agent-frontend-combined'
  _BACKEND_URL: ''
  _NEXT_PUBLIC_BACKEND_URL: ''

options:
  logging: CLOUD_LOGGING_ONLY
