steps:
  # Build the backend image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/agent-repo/${_SERVICE_NAME}:latest'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/agent-repo/${_SERVICE_NAME}:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/agent-repo/${_SERVICE_NAME}:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=${PROJECT_ID},GOOGLE_CLOUD_REGION=${_REGION}'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/agent-repo/${_SERVICE_NAME}:latest'

substitutions:
  _SERVICE_NAME: 'data-qa-agent-backend-combined'
  _REGION: 'australia-southeast2'

options:
  logging: CLOUD_LOGGING_ONLY
