steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest', '-f', 'backend/Dockerfile', 'backend/']
  
  # 2. Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest']
  
  # 3. Deploy container image to Cloud Run with dynamic URL lookup
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Deploy first
        gcloud run deploy $_SERVICE_NAME \
          --image gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest \
          --region $_REGION \
          --platform managed \
          --allow-unauthenticated
        
        # Now fetch the URL and update the environment variable for the next start/sync
        # This makes it flexible and avoids hardcoding the URL hash
        URL=$(gcloud run services describe $_SERVICE_NAME --region=$_REGION --format='value(status.url)')
        echo "Updating $_SERVICE_NAME with CLOUD_RUN_URL=$$URL"
        gcloud run services update $_SERVICE_NAME --region=$_REGION --set-env-vars "CLOUD_RUN_URL=$$URL"

substitutions:
    # These values are read from deploy.config or can be overridden in Cloud Build Trigger
    # To update: Edit deploy.config file
    _SERVICE_NAME: data-qa-agent-backend2
    _REGION: us-central1
    _PROJECT_ID: leyin-sandpit

images:
  - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest'

options:
  logging: CLOUD_LOGGING_ONLY
